### ISSUE TITLE
Update GitHub Actions workflow for proper Pages deployment

### ISSUE THREAD

**Issue by patruff** [patruff/githubFamily#5]
The current workflow needs to be updated with the following content:

```yaml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```

Changes made:
1. Added proper permissions for GitHub Pages deployment
2. Updated to use newer versions of GitHub Actions
3. Added concurrency control
4. Using official GitHub Pages deployment actions instead of third-party action

Please update the workflow file at `.github/workflows/deploy.yml` with this content.
